openapi: 3.0.2
servers:
  - url: /
info:
  title: Cribl Cloud Management API
  description: Lorem Ipsum
  version: 0.0.1
  contact:
    name: Support
    email: support@cribl.io
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /status:
    get:
      operationId: dummyServiceStatus
      summary: Service status
      responses:
        "200":
          description: OK
