"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from cribl_mgmt_plane import CriblMgmtPlane
import os
from tests.test_client import create_test_http_client


def test_criblmgmtplane_dummy_service_status():
    test_http_client = create_test_http_client("dummyServiceStatus")

    with CriblMgmtPlane(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        bearer_auth=os.getenv("CRIBLMGMTPLANE_BEARER_AUTH", "value"),
    ) as cmp_client:
        assert cmp_client is not None

        cmp_client.dummy_service_status()
