"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "cribl-mgmt-plane"
__version__: str = "0.3.0rc8"
__openapi_doc_version__: str = "1.0"
__gen_version__: str = "2.866.0"
__user_agent__: str = "speakeasy-sdk/python 0.3.0rc8 2.866.0 1.0 cribl-mgmt-plane"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
