"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from cribl_mgmt_plane.contractsutilization import ContractsUtilization
from cribl_mgmt_plane.grants import Grants
from cribl_mgmt_plane.stats import Stats
from cribl_mgmt_plane.timeseries import Timeseries
from typing import Optional


class Credits(BaseSDK):
    contracts_utilization: ContractsUtilization
    timeseries: Timeseries
    stats: Stats
    grants: Grants

    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: Optional[object] = None
    ) -> None:
        BaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.contracts_utilization = ContractsUtilization(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.timeseries = Timeseries(self.sdk_configuration, parent_ref=self.parent_ref)
        self.stats = Stats(self.sdk_configuration, parent_ref=self.parent_ref)
        self.grants = Grants(self.sdk_configuration, parent_ref=self.parent_ref)
