workflowVersion: 1.0.0
speakeasyVersion: 1.581.0
sources:
    Cribl Cloud Management API:
        inputs:
            - location: ./openapi.yml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/cribl/cribl/cribl-cloud-management-api
targets:
    cribl-mgmt-plane:
        target: python
        source: Cribl Cloud Management API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cribl/cribl/cribl-cloud-management-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
        testing:
            enabled: true
