"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane.errors import CriblMgmtPlaneError
from cribl_mgmt_plane.types import BaseModel
from dataclasses import dataclass, field
import httpx
import pydantic
from typing import Optional
from typing_extensions import Annotated


class DefaultErrorDTOData(BaseModel):
    status_code: Annotated[int, pydantic.Field(alias="statusCode")]
    r"""HTTP status code."""
    message: str
    r"""Human-readable error message."""


@dataclass(unsafe_hash=True)
class DefaultErrorDTO(CriblMgmtPlaneError):
    data: DefaultErrorDTOData = field(hash=False)

    def __init__(
        self,
        data: DefaultErrorDTOData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
