"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from cribl_mgmt_plane.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apicredentialcreaterequestdto import (
        APICredentialCreateRequestDTO,
        APICredentialCreateRequestDTOTypedDict,
    )
    from .apicredentialcreateresponseschema import (
        APICredentialCreateResponseSchema,
        APICredentialCreateResponseSchemaTypedDict,
    )
    from .apicredentialresponseschema import (
        APICredentialResponseSchema,
        APICredentialResponseSchemaTypedDict,
    )
    from .apicredentialrolesschema import (
        APICredentialRolesSchema,
        APICredentialRolesSchemaTypedDict,
        OrganizationRole,
    )
    from .apicredentialslistresponsedto import (
        APICredentialsListResponseDTO,
        APICredentialsListResponseDTOTypedDict,
    )
    from .apicredentialupdaterequestdto import (
        APICredentialUpdateRequestDTO,
        APICredentialUpdateRequestDTOTypedDict,
    )
    from .billingwindow import BillingWindow
    from .contractsutilizationresponsedto import (
        ContractsUtilizationResponseDTO,
        ContractsUtilizationResponseDTOTypedDict,
    )
    from .contractutilizationschema import (
        ContractUtilizationSchema,
        ContractUtilizationSchemaTypedDict,
    )
    from .creditgrantschema import CreditGrantSchema, CreditGrantSchemaTypedDict, Type
    from .creditgrantsresponsedto import (
        CreditGrantsResponseDTO,
        CreditGrantsResponseDTOTypedDict,
    )
    from .creditsstatscontractschema import (
        CreditsStatsContractSchema,
        CreditsStatsContractSchemaTypedDict,
    )
    from .creditsstatsresponsedto import (
        CreditsStatsResponseDTO,
        CreditsStatsResponseDTOTypedDict,
    )
    from .creditstimeseriesdimensionschema import (
        CreditsTimeseriesDimensionSchema,
        CreditsTimeseriesDimensionSchemaTypedDict,
    )
    from .creditstimeseriesitemschema import (
        CreditsTimeseriesItemSchema,
        CreditsTimeseriesItemSchemaTypedDict,
    )
    from .creditstimeseriesresponsedto import (
        CreditsTimeseriesResponseDTO,
        CreditsTimeseriesResponseDTOTypedDict,
    )
    from .creditsutilizationitemschema import (
        CreditsUtilizationItemSchema,
        CreditsUtilizationItemSchemaTypedDict,
    )
    from .defaulterrordto import DefaultErrorDTO, DefaultErrorDTOTypedDict
    from .gethealthstatusop import (
        GetHealthStatusResponse,
        GetHealthStatusResponseBody,
        GetHealthStatusResponseBodyTypedDict,
        GetHealthStatusResponseTypedDict,
    )
    from .productroleschema import (
        Product,
        ProductRoleSchema,
        ProductRoleSchemaTypedDict,
        Role,
    )
    from .schemeclientoauth import SchemeClientOauth, SchemeClientOauthTypedDict
    from .security import Security, SecurityTypedDict
    from .v1_apicredentials_createapicredentialop import (
        V1APICredentialsCreateAPICredentialRequest,
        V1APICredentialsCreateAPICredentialRequestTypedDict,
        V1APICredentialsCreateAPICredentialResponse,
        V1APICredentialsCreateAPICredentialResponseTypedDict,
    )
    from .v1_apicredentials_deleteapicredentialop import (
        V1APICredentialsDeleteAPICredentialRequest,
        V1APICredentialsDeleteAPICredentialRequestTypedDict,
    )
    from .v1_apicredentials_getapicredentialop import (
        V1APICredentialsGetAPICredentialRequest,
        V1APICredentialsGetAPICredentialRequestTypedDict,
        V1APICredentialsGetAPICredentialResponse,
        V1APICredentialsGetAPICredentialResponseTypedDict,
    )
    from .v1_apicredentials_listapicredentialsop import (
        V1APICredentialsListAPICredentialsRequest,
        V1APICredentialsListAPICredentialsRequestTypedDict,
        V1APICredentialsListAPICredentialsResponse,
        V1APICredentialsListAPICredentialsResponseTypedDict,
    )
    from .v1_apicredentials_updateapicredentialop import (
        V1APICredentialsUpdateAPICredentialRequest,
        V1APICredentialsUpdateAPICredentialRequestTypedDict,
    )
    from .v1_billing_getcontractsutilizationop import (
        V1BillingGetContractsUtilizationRequest,
        V1BillingGetContractsUtilizationRequestTypedDict,
        V1BillingGetContractsUtilizationResponse,
        V1BillingGetContractsUtilizationResponseTypedDict,
    )
    from .v1_billing_getcreditsgrantsop import (
        V1BillingGetCreditsGrantsRequest,
        V1BillingGetCreditsGrantsRequestTypedDict,
        V1BillingGetCreditsGrantsResponse,
        V1BillingGetCreditsGrantsResponseTypedDict,
    )
    from .v1_billing_getcreditsstatsop import (
        V1BillingGetCreditsStatsRequest,
        V1BillingGetCreditsStatsRequestTypedDict,
        V1BillingGetCreditsStatsResponse,
        V1BillingGetCreditsStatsResponseTypedDict,
    )
    from .v1_billing_getcreditstimeseriesop import (
        V1BillingGetCreditsTimeseriesRequest,
        V1BillingGetCreditsTimeseriesRequestTypedDict,
        V1BillingGetCreditsTimeseriesResponse,
        V1BillingGetCreditsTimeseriesResponseTypedDict,
    )
    from .v1_workspaces_createworkspaceop import (
        V1WorkspacesCreateWorkspaceRequest,
        V1WorkspacesCreateWorkspaceRequestTypedDict,
        V1WorkspacesCreateWorkspaceResponse,
        V1WorkspacesCreateWorkspaceResponseTypedDict,
    )
    from .v1_workspaces_deleteworkspaceop import (
        V1WorkspacesDeleteWorkspaceRequest,
        V1WorkspacesDeleteWorkspaceRequestTypedDict,
    )
    from .v1_workspaces_getworkspaceop import (
        V1WorkspacesGetWorkspaceRequest,
        V1WorkspacesGetWorkspaceRequestTypedDict,
        V1WorkspacesGetWorkspaceResponse,
        V1WorkspacesGetWorkspaceResponseTypedDict,
    )
    from .v1_workspaces_listworkspacesop import (
        V1WorkspacesListWorkspacesRequest,
        V1WorkspacesListWorkspacesRequestTypedDict,
        V1WorkspacesListWorkspacesResponse,
        V1WorkspacesListWorkspacesResponseTypedDict,
    )
    from .v1_workspaces_updateworkspaceop import (
        V1WorkspacesUpdateWorkspaceRequest,
        V1WorkspacesUpdateWorkspaceRequestTypedDict,
    )
    from .workspacecreaterequestdto import (
        WorkspaceCreateRequestDTO,
        WorkspaceCreateRequestDTOTypedDict,
    )
    from .workspacepatchrequestdto import (
        WorkspacePatchRequestDTO,
        WorkspacePatchRequestDTOTypedDict,
    )
    from .workspaceroleschema import (
        WorkspaceRole,
        WorkspaceRoleSchema,
        WorkspaceRoleSchemaTypedDict,
    )
    from .workspaceschema import (
        Region,
        State,
        WorkspaceSchema,
        WorkspaceSchemaTypedDict,
    )
    from .workspaceslistresponsedto import (
        WorkspacesListResponseDTO,
        WorkspacesListResponseDTOTypedDict,
    )

__all__ = [
    "APICredentialCreateRequestDTO",
    "APICredentialCreateRequestDTOTypedDict",
    "APICredentialCreateResponseSchema",
    "APICredentialCreateResponseSchemaTypedDict",
    "APICredentialResponseSchema",
    "APICredentialResponseSchemaTypedDict",
    "APICredentialRolesSchema",
    "APICredentialRolesSchemaTypedDict",
    "APICredentialUpdateRequestDTO",
    "APICredentialUpdateRequestDTOTypedDict",
    "APICredentialsListResponseDTO",
    "APICredentialsListResponseDTOTypedDict",
    "BillingWindow",
    "ContractUtilizationSchema",
    "ContractUtilizationSchemaTypedDict",
    "ContractsUtilizationResponseDTO",
    "ContractsUtilizationResponseDTOTypedDict",
    "CreditGrantSchema",
    "CreditGrantSchemaTypedDict",
    "CreditGrantsResponseDTO",
    "CreditGrantsResponseDTOTypedDict",
    "CreditsStatsContractSchema",
    "CreditsStatsContractSchemaTypedDict",
    "CreditsStatsResponseDTO",
    "CreditsStatsResponseDTOTypedDict",
    "CreditsTimeseriesDimensionSchema",
    "CreditsTimeseriesDimensionSchemaTypedDict",
    "CreditsTimeseriesItemSchema",
    "CreditsTimeseriesItemSchemaTypedDict",
    "CreditsTimeseriesResponseDTO",
    "CreditsTimeseriesResponseDTOTypedDict",
    "CreditsUtilizationItemSchema",
    "CreditsUtilizationItemSchemaTypedDict",
    "DefaultErrorDTO",
    "DefaultErrorDTOTypedDict",
    "GetHealthStatusResponse",
    "GetHealthStatusResponseBody",
    "GetHealthStatusResponseBodyTypedDict",
    "GetHealthStatusResponseTypedDict",
    "OrganizationRole",
    "Product",
    "ProductRoleSchema",
    "ProductRoleSchemaTypedDict",
    "Region",
    "Role",
    "SchemeClientOauth",
    "SchemeClientOauthTypedDict",
    "Security",
    "SecurityTypedDict",
    "State",
    "Type",
    "V1APICredentialsCreateAPICredentialRequest",
    "V1APICredentialsCreateAPICredentialRequestTypedDict",
    "V1APICredentialsCreateAPICredentialResponse",
    "V1APICredentialsCreateAPICredentialResponseTypedDict",
    "V1APICredentialsDeleteAPICredentialRequest",
    "V1APICredentialsDeleteAPICredentialRequestTypedDict",
    "V1APICredentialsGetAPICredentialRequest",
    "V1APICredentialsGetAPICredentialRequestTypedDict",
    "V1APICredentialsGetAPICredentialResponse",
    "V1APICredentialsGetAPICredentialResponseTypedDict",
    "V1APICredentialsListAPICredentialsRequest",
    "V1APICredentialsListAPICredentialsRequestTypedDict",
    "V1APICredentialsListAPICredentialsResponse",
    "V1APICredentialsListAPICredentialsResponseTypedDict",
    "V1APICredentialsUpdateAPICredentialRequest",
    "V1APICredentialsUpdateAPICredentialRequestTypedDict",
    "V1BillingGetContractsUtilizationRequest",
    "V1BillingGetContractsUtilizationRequestTypedDict",
    "V1BillingGetContractsUtilizationResponse",
    "V1BillingGetContractsUtilizationResponseTypedDict",
    "V1BillingGetCreditsGrantsRequest",
    "V1BillingGetCreditsGrantsRequestTypedDict",
    "V1BillingGetCreditsGrantsResponse",
    "V1BillingGetCreditsGrantsResponseTypedDict",
    "V1BillingGetCreditsStatsRequest",
    "V1BillingGetCreditsStatsRequestTypedDict",
    "V1BillingGetCreditsStatsResponse",
    "V1BillingGetCreditsStatsResponseTypedDict",
    "V1BillingGetCreditsTimeseriesRequest",
    "V1BillingGetCreditsTimeseriesRequestTypedDict",
    "V1BillingGetCreditsTimeseriesResponse",
    "V1BillingGetCreditsTimeseriesResponseTypedDict",
    "V1WorkspacesCreateWorkspaceRequest",
    "V1WorkspacesCreateWorkspaceRequestTypedDict",
    "V1WorkspacesCreateWorkspaceResponse",
    "V1WorkspacesCreateWorkspaceResponseTypedDict",
    "V1WorkspacesDeleteWorkspaceRequest",
    "V1WorkspacesDeleteWorkspaceRequestTypedDict",
    "V1WorkspacesGetWorkspaceRequest",
    "V1WorkspacesGetWorkspaceRequestTypedDict",
    "V1WorkspacesGetWorkspaceResponse",
    "V1WorkspacesGetWorkspaceResponseTypedDict",
    "V1WorkspacesListWorkspacesRequest",
    "V1WorkspacesListWorkspacesRequestTypedDict",
    "V1WorkspacesListWorkspacesResponse",
    "V1WorkspacesListWorkspacesResponseTypedDict",
    "V1WorkspacesUpdateWorkspaceRequest",
    "V1WorkspacesUpdateWorkspaceRequestTypedDict",
    "WorkspaceCreateRequestDTO",
    "WorkspaceCreateRequestDTOTypedDict",
    "WorkspacePatchRequestDTO",
    "WorkspacePatchRequestDTOTypedDict",
    "WorkspaceRole",
    "WorkspaceRoleSchema",
    "WorkspaceRoleSchemaTypedDict",
    "WorkspaceSchema",
    "WorkspaceSchemaTypedDict",
    "WorkspacesListResponseDTO",
    "WorkspacesListResponseDTOTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "APICredentialCreateRequestDTO": ".apicredentialcreaterequestdto",
    "APICredentialCreateRequestDTOTypedDict": ".apicredentialcreaterequestdto",
    "APICredentialCreateResponseSchema": ".apicredentialcreateresponseschema",
    "APICredentialCreateResponseSchemaTypedDict": ".apicredentialcreateresponseschema",
    "APICredentialResponseSchema": ".apicredentialresponseschema",
    "APICredentialResponseSchemaTypedDict": ".apicredentialresponseschema",
    "APICredentialRolesSchema": ".apicredentialrolesschema",
    "APICredentialRolesSchemaTypedDict": ".apicredentialrolesschema",
    "OrganizationRole": ".apicredentialrolesschema",
    "APICredentialsListResponseDTO": ".apicredentialslistresponsedto",
    "APICredentialsListResponseDTOTypedDict": ".apicredentialslistresponsedto",
    "APICredentialUpdateRequestDTO": ".apicredentialupdaterequestdto",
    "APICredentialUpdateRequestDTOTypedDict": ".apicredentialupdaterequestdto",
    "BillingWindow": ".billingwindow",
    "ContractsUtilizationResponseDTO": ".contractsutilizationresponsedto",
    "ContractsUtilizationResponseDTOTypedDict": ".contractsutilizationresponsedto",
    "ContractUtilizationSchema": ".contractutilizationschema",
    "ContractUtilizationSchemaTypedDict": ".contractutilizationschema",
    "CreditGrantSchema": ".creditgrantschema",
    "CreditGrantSchemaTypedDict": ".creditgrantschema",
    "Type": ".creditgrantschema",
    "CreditGrantsResponseDTO": ".creditgrantsresponsedto",
    "CreditGrantsResponseDTOTypedDict": ".creditgrantsresponsedto",
    "CreditsStatsContractSchema": ".creditsstatscontractschema",
    "CreditsStatsContractSchemaTypedDict": ".creditsstatscontractschema",
    "CreditsStatsResponseDTO": ".creditsstatsresponsedto",
    "CreditsStatsResponseDTOTypedDict": ".creditsstatsresponsedto",
    "CreditsTimeseriesDimensionSchema": ".creditstimeseriesdimensionschema",
    "CreditsTimeseriesDimensionSchemaTypedDict": ".creditstimeseriesdimensionschema",
    "CreditsTimeseriesItemSchema": ".creditstimeseriesitemschema",
    "CreditsTimeseriesItemSchemaTypedDict": ".creditstimeseriesitemschema",
    "CreditsTimeseriesResponseDTO": ".creditstimeseriesresponsedto",
    "CreditsTimeseriesResponseDTOTypedDict": ".creditstimeseriesresponsedto",
    "CreditsUtilizationItemSchema": ".creditsutilizationitemschema",
    "CreditsUtilizationItemSchemaTypedDict": ".creditsutilizationitemschema",
    "DefaultErrorDTO": ".defaulterrordto",
    "DefaultErrorDTOTypedDict": ".defaulterrordto",
    "GetHealthStatusResponse": ".gethealthstatusop",
    "GetHealthStatusResponseBody": ".gethealthstatusop",
    "GetHealthStatusResponseBodyTypedDict": ".gethealthstatusop",
    "GetHealthStatusResponseTypedDict": ".gethealthstatusop",
    "Product": ".productroleschema",
    "ProductRoleSchema": ".productroleschema",
    "ProductRoleSchemaTypedDict": ".productroleschema",
    "Role": ".productroleschema",
    "SchemeClientOauth": ".schemeclientoauth",
    "SchemeClientOauthTypedDict": ".schemeclientoauth",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "V1APICredentialsCreateAPICredentialRequest": ".v1_apicredentials_createapicredentialop",
    "V1APICredentialsCreateAPICredentialRequestTypedDict": ".v1_apicredentials_createapicredentialop",
    "V1APICredentialsCreateAPICredentialResponse": ".v1_apicredentials_createapicredentialop",
    "V1APICredentialsCreateAPICredentialResponseTypedDict": ".v1_apicredentials_createapicredentialop",
    "V1APICredentialsDeleteAPICredentialRequest": ".v1_apicredentials_deleteapicredentialop",
    "V1APICredentialsDeleteAPICredentialRequestTypedDict": ".v1_apicredentials_deleteapicredentialop",
    "V1APICredentialsGetAPICredentialRequest": ".v1_apicredentials_getapicredentialop",
    "V1APICredentialsGetAPICredentialRequestTypedDict": ".v1_apicredentials_getapicredentialop",
    "V1APICredentialsGetAPICredentialResponse": ".v1_apicredentials_getapicredentialop",
    "V1APICredentialsGetAPICredentialResponseTypedDict": ".v1_apicredentials_getapicredentialop",
    "V1APICredentialsListAPICredentialsRequest": ".v1_apicredentials_listapicredentialsop",
    "V1APICredentialsListAPICredentialsRequestTypedDict": ".v1_apicredentials_listapicredentialsop",
    "V1APICredentialsListAPICredentialsResponse": ".v1_apicredentials_listapicredentialsop",
    "V1APICredentialsListAPICredentialsResponseTypedDict": ".v1_apicredentials_listapicredentialsop",
    "V1APICredentialsUpdateAPICredentialRequest": ".v1_apicredentials_updateapicredentialop",
    "V1APICredentialsUpdateAPICredentialRequestTypedDict": ".v1_apicredentials_updateapicredentialop",
    "V1BillingGetContractsUtilizationRequest": ".v1_billing_getcontractsutilizationop",
    "V1BillingGetContractsUtilizationRequestTypedDict": ".v1_billing_getcontractsutilizationop",
    "V1BillingGetContractsUtilizationResponse": ".v1_billing_getcontractsutilizationop",
    "V1BillingGetContractsUtilizationResponseTypedDict": ".v1_billing_getcontractsutilizationop",
    "V1BillingGetCreditsGrantsRequest": ".v1_billing_getcreditsgrantsop",
    "V1BillingGetCreditsGrantsRequestTypedDict": ".v1_billing_getcreditsgrantsop",
    "V1BillingGetCreditsGrantsResponse": ".v1_billing_getcreditsgrantsop",
    "V1BillingGetCreditsGrantsResponseTypedDict": ".v1_billing_getcreditsgrantsop",
    "V1BillingGetCreditsStatsRequest": ".v1_billing_getcreditsstatsop",
    "V1BillingGetCreditsStatsRequestTypedDict": ".v1_billing_getcreditsstatsop",
    "V1BillingGetCreditsStatsResponse": ".v1_billing_getcreditsstatsop",
    "V1BillingGetCreditsStatsResponseTypedDict": ".v1_billing_getcreditsstatsop",
    "V1BillingGetCreditsTimeseriesRequest": ".v1_billing_getcreditstimeseriesop",
    "V1BillingGetCreditsTimeseriesRequestTypedDict": ".v1_billing_getcreditstimeseriesop",
    "V1BillingGetCreditsTimeseriesResponse": ".v1_billing_getcreditstimeseriesop",
    "V1BillingGetCreditsTimeseriesResponseTypedDict": ".v1_billing_getcreditstimeseriesop",
    "V1WorkspacesCreateWorkspaceRequest": ".v1_workspaces_createworkspaceop",
    "V1WorkspacesCreateWorkspaceRequestTypedDict": ".v1_workspaces_createworkspaceop",
    "V1WorkspacesCreateWorkspaceResponse": ".v1_workspaces_createworkspaceop",
    "V1WorkspacesCreateWorkspaceResponseTypedDict": ".v1_workspaces_createworkspaceop",
    "V1WorkspacesDeleteWorkspaceRequest": ".v1_workspaces_deleteworkspaceop",
    "V1WorkspacesDeleteWorkspaceRequestTypedDict": ".v1_workspaces_deleteworkspaceop",
    "V1WorkspacesGetWorkspaceRequest": ".v1_workspaces_getworkspaceop",
    "V1WorkspacesGetWorkspaceRequestTypedDict": ".v1_workspaces_getworkspaceop",
    "V1WorkspacesGetWorkspaceResponse": ".v1_workspaces_getworkspaceop",
    "V1WorkspacesGetWorkspaceResponseTypedDict": ".v1_workspaces_getworkspaceop",
    "V1WorkspacesListWorkspacesRequest": ".v1_workspaces_listworkspacesop",
    "V1WorkspacesListWorkspacesRequestTypedDict": ".v1_workspaces_listworkspacesop",
    "V1WorkspacesListWorkspacesResponse": ".v1_workspaces_listworkspacesop",
    "V1WorkspacesListWorkspacesResponseTypedDict": ".v1_workspaces_listworkspacesop",
    "V1WorkspacesUpdateWorkspaceRequest": ".v1_workspaces_updateworkspaceop",
    "V1WorkspacesUpdateWorkspaceRequestTypedDict": ".v1_workspaces_updateworkspaceop",
    "WorkspaceCreateRequestDTO": ".workspacecreaterequestdto",
    "WorkspaceCreateRequestDTOTypedDict": ".workspacecreaterequestdto",
    "WorkspacePatchRequestDTO": ".workspacepatchrequestdto",
    "WorkspacePatchRequestDTOTypedDict": ".workspacepatchrequestdto",
    "WorkspaceRole": ".workspaceroleschema",
    "WorkspaceRoleSchema": ".workspaceroleschema",
    "WorkspaceRoleSchemaTypedDict": ".workspaceroleschema",
    "Region": ".workspaceschema",
    "State": ".workspaceschema",
    "WorkspaceSchema": ".workspaceschema",
    "WorkspaceSchemaTypedDict": ".workspaceschema",
    "WorkspacesListResponseDTO": ".workspaceslistresponsedto",
    "WorkspacesListResponseDTOTypedDict": ".workspaceslistresponsedto",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
