"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apicredentialrolesschema import (
    APICredentialRolesSchema,
    APICredentialRolesSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class APICredentialListItemSchemaTypedDict(TypedDict):
    name: str
    r"""Human-readable name of the API Credential."""
    description: str
    r"""Brief description of the purpose and usage for the API Credential."""
    enabled: bool
    r"""If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>."""
    workspace_id: str
    r"""Unique ID of the Workspace."""
    organization_id: str
    r"""Unique ID of the Organization."""
    client_id: str
    r"""Client ID for the API Credential."""
    roles: APICredentialRolesSchemaTypedDict
    r"""Role assignments for the API Credential."""
    created_by: str
    r"""Member who created the API Credential."""
    created_date: str
    r"""ISO 8601 timestamp when the API Credential was created."""
    last_updated_by: str
    r"""Member who last updated the API Credential."""
    last_updated_date: str
    r"""ISO 8601 timestamp when the API Credential was last updated."""


class APICredentialListItemSchema(BaseModel):
    name: str
    r"""Human-readable name of the API Credential."""

    description: str
    r"""Brief description of the purpose and usage for the API Credential."""

    enabled: bool
    r"""If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>."""

    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]
    r"""Unique ID of the Workspace."""

    organization_id: Annotated[str, pydantic.Field(alias="organizationId")]
    r"""Unique ID of the Organization."""

    client_id: Annotated[str, pydantic.Field(alias="clientId")]
    r"""Client ID for the API Credential."""

    roles: APICredentialRolesSchema
    r"""Role assignments for the API Credential."""

    created_by: Annotated[str, pydantic.Field(alias="createdBy")]
    r"""Member who created the API Credential."""

    created_date: Annotated[str, pydantic.Field(alias="createdDate")]
    r"""ISO 8601 timestamp when the API Credential was created."""

    last_updated_by: Annotated[str, pydantic.Field(alias="lastUpdatedBy")]
    r"""Member who last updated the API Credential."""

    last_updated_date: Annotated[str, pydantic.Field(alias="lastUpdatedDate")]
    r"""ISO 8601 timestamp when the API Credential was last updated."""


try:
    APICredentialListItemSchema.model_rebuild()
except NameError:
    pass
