"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workspaceroleschema import WorkspaceRoleSchema, WorkspaceRoleSchemaTypedDict
from cribl_mgmt_plane import models, utils
from cribl_mgmt_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OrganizationRole(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Organization-level role"""

    OWNER = "owner"
    ADMIN = "admin"
    USER = "user"


class APICredentialRolesSchemaTypedDict(TypedDict):
    organization_role: OrganizationRole
    r"""Organization-level role"""
    workspaces: NotRequired[List[WorkspaceRoleSchemaTypedDict]]
    r"""Workspace roles assigned to this credential"""


class APICredentialRolesSchema(BaseModel):
    organization_role: Annotated[
        OrganizationRole, pydantic.Field(alias="organizationRole")
    ]
    r"""Organization-level role"""

    workspaces: Optional[List[WorkspaceRoleSchema]] = None
    r"""Workspace roles assigned to this credential"""

    @field_serializer("organization_role")
    def serialize_organization_role(self, value):
        if isinstance(value, str):
            try:
                return models.OrganizationRole(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["workspaces"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
