"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apicredentiallistitemschema import (
    APICredentialListItemSchema,
    APICredentialListItemSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class APICredentialsListResponseDTOTypedDict(TypedDict):
    items: List[APICredentialListItemSchemaTypedDict]
    r"""List of API Credentials."""
    count: float
    r"""Total number of API Credentials listed in the response."""


class APICredentialsListResponseDTO(BaseModel):
    items: List[APICredentialListItemSchema]
    r"""List of API Credentials."""

    count: float
    r"""Total number of API Credentials listed in the response."""
