"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apicredentialrolesschema import (
    APICredentialRolesSchema,
    APICredentialRolesSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel
from datetime import datetime
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class APICredentialResponseSchemaTypedDict(TypedDict):
    name: str
    r"""Human-readable name of the API Credential."""
    description: str
    r"""Brief description of the purpose and usage for the API Credential."""
    enabled: bool
    r"""If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>."""
    organization_id: str
    r"""Unique ID of the Organization."""
    client_id: str
    r"""Client ID for the API Credential."""
    roles: APICredentialRolesSchemaTypedDict
    r"""Role assignments for the API Credential."""
    ip_allowlist: List[str]
    r"""CIDR range enforced as the IP allowlist for the API Credential. An empty array means that the API Credential has no IP restrictions."""
    created_by: str
    r"""Member who created the API Credential."""
    created_date: datetime
    r"""ISO 8601 timestamp when the API Credential was created."""
    last_updated_by: str
    r"""Member who last updated the API Credential."""
    last_updated_date: datetime
    r"""ISO 8601 timestamp when the API Credential was last updated."""


class APICredentialResponseSchema(BaseModel):
    name: str
    r"""Human-readable name of the API Credential."""

    description: str
    r"""Brief description of the purpose and usage for the API Credential."""

    enabled: bool
    r"""If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>."""

    organization_id: Annotated[str, pydantic.Field(alias="organizationId")]
    r"""Unique ID of the Organization."""

    client_id: Annotated[str, pydantic.Field(alias="clientId")]
    r"""Client ID for the API Credential."""

    roles: APICredentialRolesSchema
    r"""Role assignments for the API Credential."""

    ip_allowlist: Annotated[List[str], pydantic.Field(alias="ipAllowlist")]
    r"""CIDR range enforced as the IP allowlist for the API Credential. An empty array means that the API Credential has no IP restrictions."""

    created_by: Annotated[str, pydantic.Field(alias="createdBy")]
    r"""Member who created the API Credential."""

    created_date: Annotated[datetime, pydantic.Field(alias="createdDate")]
    r"""ISO 8601 timestamp when the API Credential was created."""

    last_updated_by: Annotated[str, pydantic.Field(alias="lastUpdatedBy")]
    r"""Member who last updated the API Credential."""

    last_updated_date: Annotated[datetime, pydantic.Field(alias="lastUpdatedDate")]
    r"""ISO 8601 timestamp when the API Credential was last updated."""


try:
    APICredentialResponseSchema.model_rebuild()
except NameError:
    pass
