"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apicredentialresponseschema import (
    APICredentialResponseSchema,
    APICredentialResponseSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class APICredentialsListResponseDTOTypedDict(TypedDict):
    items: List[APICredentialResponseSchemaTypedDict]
    r"""List of API Credentials."""
    count: int
    r"""Total number of API Credentials listed in the response."""


class APICredentialsListResponseDTO(BaseModel):
    items: List[APICredentialResponseSchema]
    r"""List of API Credentials."""

    count: int
    r"""Total number of API Credentials listed in the response."""
