"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apicredentialrolesschema import (
    APICredentialRolesSchema,
    APICredentialRolesSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class APICredentialSchemaTypedDict(TypedDict):
    name: str
    r"""Human friendly name of the credential"""
    description: str
    r"""Description of how or where the credential is used"""
    enabled: bool
    r"""Whether the credential is enabled"""
    workspace_id: str
    r"""Workspace identifier"""
    organization_id: str
    r"""Organization identifier"""
    client_id: str
    r"""Client identifier"""
    client_secret: str
    r"""Client secret"""
    roles: APICredentialRolesSchemaTypedDict
    r"""Role assignments for this credential"""
    created_by: str
    r"""User who created the credential"""
    created_date: str
    r"""ISO-8601 timestamp when the credential was created"""
    last_updated_by: str
    r"""User who last updated the credential"""
    last_updated_date: str
    r"""ISO-8601 timestamp when the credential was last updated"""


class APICredentialSchema(BaseModel):
    name: str
    r"""Human friendly name of the credential"""

    description: str
    r"""Description of how or where the credential is used"""

    enabled: bool
    r"""Whether the credential is enabled"""

    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]
    r"""Workspace identifier"""

    organization_id: Annotated[str, pydantic.Field(alias="organizationId")]
    r"""Organization identifier"""

    client_id: Annotated[str, pydantic.Field(alias="clientId")]
    r"""Client identifier"""

    client_secret: Annotated[str, pydantic.Field(alias="clientSecret")]
    r"""Client secret"""

    roles: APICredentialRolesSchema
    r"""Role assignments for this credential"""

    created_by: Annotated[str, pydantic.Field(alias="createdBy")]
    r"""User who created the credential"""

    created_date: Annotated[str, pydantic.Field(alias="createdDate")]
    r"""ISO-8601 timestamp when the credential was created"""

    last_updated_by: Annotated[str, pydantic.Field(alias="lastUpdatedBy")]
    r"""User who last updated the credential"""

    last_updated_date: Annotated[str, pydantic.Field(alias="lastUpdatedDate")]
    r"""ISO-8601 timestamp when the credential was last updated"""
