"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apicredentialrolesschema import (
    APICredentialRolesSchema,
    APICredentialRolesSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class APICredentialUpdateRequestDTOTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Human-readable name of the API Credential."""
    description: NotRequired[str]
    r"""Brief description of the purpose and usage for the API Credential."""
    enabled: NotRequired[bool]
    r"""If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>."""
    roles: NotRequired[APICredentialRolesSchemaTypedDict]
    r"""Role assignments for the API Credential."""


class APICredentialUpdateRequestDTO(BaseModel):
    name: Optional[str] = None
    r"""Human-readable name of the API Credential."""

    description: Optional[str] = None
    r"""Brief description of the purpose and usage for the API Credential."""

    enabled: Optional[bool] = None
    r"""If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>."""

    roles: Optional[APICredentialRolesSchema] = None
    r"""Role assignments for the API Credential."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "description", "enabled", "roles"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
