"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apicredentialrolesschema import (
    APICredentialRolesSchema,
    APICredentialRolesSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class APICredentialCreateRequestDTOTypedDict(TypedDict):
    name: str
    r"""Human-readable name of the API Credential."""
    description: str
    r"""Brief description of the purpose and usage for the API Credential."""
    enabled: bool
    r"""If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>."""
    workspace_id: str
    r"""Unique ID of the Workspace."""
    roles: APICredentialRolesSchemaTypedDict
    r"""Role assignments for the API Credential."""


class APICredentialCreateRequestDTO(BaseModel):
    name: str
    r"""Human-readable name of the API Credential."""

    description: str
    r"""Brief description of the purpose and usage for the API Credential."""

    enabled: bool
    r"""If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>."""

    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]
    r"""Unique ID of the Workspace."""

    roles: APICredentialRolesSchema
    r"""Role assignments for the API Credential."""
