"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane import utils
from enum import Enum


class BillingWindow(str, Enum, metaclass=utils.OpenEnumMeta):
    MONTHLY = "monthly"
    DAILY = "daily"
