"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .contractutilizationschema import (
    ContractUtilizationSchema,
    ContractUtilizationSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ContractsUtilizationResponseDTOTypedDict(TypedDict):
    contracts: List[ContractUtilizationSchemaTypedDict]
    r"""Contract utilization data, grouped by contract period."""


class ContractsUtilizationResponseDTO(BaseModel):
    contracts: List[ContractUtilizationSchema]
    r"""Contract utilization data, grouped by contract period."""
