"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creditsstatscontractschema import (
    CreditsStatsContractSchema,
    CreditsStatsContractSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreditsStatsResponseDTOTypedDict(TypedDict):
    total_credits_remaining: float
    r"""Total credits remaining across all contracts."""
    total_credits_used: float
    r"""Total credits consumed across all contracts."""
    total_credits_acquired: float
    r"""Total credits acquired across all contracts."""
    contracts: NotRequired[List[CreditsStatsContractSchemaTypedDict]]
    r"""Contract periods ordered by contract start date in reverse chronological order (newest first)."""


class CreditsStatsResponseDTO(BaseModel):
    total_credits_remaining: Annotated[
        float, pydantic.Field(alias="totalCreditsRemaining")
    ]
    r"""Total credits remaining across all contracts."""

    total_credits_used: Annotated[float, pydantic.Field(alias="totalCreditsUsed")]
    r"""Total credits consumed across all contracts."""

    total_credits_acquired: Annotated[
        float, pydantic.Field(alias="totalCreditsAcquired")
    ]
    r"""Total credits acquired across all contracts."""

    contracts: Optional[List[CreditsStatsContractSchema]] = None
    r"""Contract periods ordered by contract start date in reverse chronological order (newest first)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contracts"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreditsStatsResponseDTO.model_rebuild()
except NameError:
    pass
