"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreditsStatsContractSchemaTypedDict(TypedDict):
    start_date: datetime
    r"""Contract start date in ISO 8601 format."""
    end_date: NotRequired[datetime]
    r"""Contract end date in ISO 8601 format. Present only when the contract is closed."""


class CreditsStatsContractSchema(BaseModel):
    start_date: Annotated[datetime, pydantic.Field(alias="startDate")]
    r"""Contract start date in ISO 8601 format."""

    end_date: Annotated[Optional[datetime], pydantic.Field(alias="endDate")] = None
    r"""Contract end date in ISO 8601 format. Present only when the contract is closed."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["endDate"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreditsStatsContractSchema.model_rebuild()
except NameError:
    pass
