"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creditstimeseriesdimensionschema import (
    CreditsTimeseriesDimensionSchema,
    CreditsTimeseriesDimensionSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel
from datetime import datetime
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class CreditsTimeseriesItemSchemaTypedDict(TypedDict):
    date_: datetime
    r"""Date of the aggregation window in ISO 8601 format."""
    credits: float
    r"""Total credits consumed in the aggregation window."""
    dimensions: List[CreditsTimeseriesDimensionSchemaTypedDict]
    r"""Credit breakdown by dimension."""


class CreditsTimeseriesItemSchema(BaseModel):
    date_: Annotated[datetime, pydantic.Field(alias="date")]
    r"""Date of the aggregation window in ISO 8601 format."""

    credits: float
    r"""Total credits consumed in the aggregation window."""

    dimensions: List[CreditsTimeseriesDimensionSchema]
    r"""Credit breakdown by dimension."""


try:
    CreditsTimeseriesItemSchema.model_rebuild()
except NameError:
    pass
