"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creditgrantschema import CreditGrantSchema, CreditGrantSchemaTypedDict
from cribl_mgmt_plane.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CreditGrantsResponseDTOTypedDict(TypedDict):
    items: List[CreditGrantSchemaTypedDict]
    r"""Credit grants for the current contract. Listed in reverse chronologial order by grant date (newest first)."""
    count: int
    r"""Total number of items in the response."""


class CreditGrantsResponseDTO(BaseModel):
    items: List[CreditGrantSchema]
    r"""Credit grants for the current contract. Listed in reverse chronologial order by grant date (newest first)."""

    count: int
    r"""Total number of items in the response."""
