"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creditstimeseriesitemschema import (
    CreditsTimeseriesItemSchema,
    CreditsTimeseriesItemSchemaTypedDict,
)
from cribl_mgmt_plane.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CreditsTimeseriesResponseDTOTypedDict(TypedDict):
    items: List[CreditsTimeseriesItemSchemaTypedDict]
    r"""Credit timeseries data points."""
    count: int
    r"""Total number of items in the response."""


class CreditsTimeseriesResponseDTO(BaseModel):
    items: List[CreditsTimeseriesItemSchema]
    r"""Credit timeseries data points."""

    count: int
    r"""Total number of items in the response."""
