"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane.types import BaseModel
from typing_extensions import TypedDict


class CreditsTimeseriesDimensionSchemaTypedDict(TypedDict):
    dimension: str
    r"""Dimension label for the credit breakdown."""
    credits: float
    r"""Number of credits attributed to the dimension."""


class CreditsTimeseriesDimensionSchema(BaseModel):
    dimension: str
    r"""Dimension label for the credit breakdown."""

    credits: float
    r"""Number of credits attributed to the dimension."""
