"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane import models, utils
from cribl_mgmt_plane.types import BaseModel
from datetime import datetime
from enum import Enum
import pydantic
from pydantic import field_serializer
from typing_extensions import Annotated, TypedDict


class Type(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Type of the credit grant."""

    REFUND = "Refund"
    ROLLOVER = "Rollover"
    PURCHASED = "Purchased"


class CreditGrantSchemaTypedDict(TypedDict):
    date_: datetime
    r"""Date the grant was issued, in ISO 8601 format."""
    credits_acquired: float
    r"""Number of credits acquired by the grant."""
    type: Type
    r"""Type of the credit grant."""


class CreditGrantSchema(BaseModel):
    date_: Annotated[datetime, pydantic.Field(alias="date")]
    r"""Date the grant was issued, in ISO 8601 format."""

    credits_acquired: Annotated[float, pydantic.Field(alias="creditsAcquired")]
    r"""Number of credits acquired by the grant."""

    type: Type
    r"""Type of the credit grant."""

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return models.Type(value)
            except ValueError:
                return value
        return value


try:
    CreditGrantSchema.model_rebuild()
except NameError:
    pass
