"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane.types import BaseModel
from datetime import datetime
import pydantic
from typing_extensions import Annotated, TypedDict


class CreditsUtilizationItemSchemaTypedDict(TypedDict):
    date_: datetime
    r"""Date of the aggregation window in ISO 8601 format."""
    credits: float
    r"""Number of credits consumed in the aggregation window."""


class CreditsUtilizationItemSchema(BaseModel):
    date_: Annotated[datetime, pydantic.Field(alias="date")]
    r"""Date of the aggregation window in ISO 8601 format."""

    credits: float
    r"""Number of credits consumed in the aggregation window."""


try:
    CreditsUtilizationItemSchema.model_rebuild()
except NameError:
    pass
