"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class DefaultErrorDTOTypedDict(TypedDict):
    status_code: int
    r"""HTTP status code."""
    message: str
    r"""Human-readable error message."""


class DefaultErrorDTO(BaseModel):
    status_code: Annotated[int, pydantic.Field(alias="statusCode")]
    r"""HTTP status code."""

    message: str
    r"""Human-readable error message."""


try:
    DefaultErrorDTO.model_rebuild()
except NameError:
    pass
