"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane import models, utils
from cribl_mgmt_plane.types import BaseModel
from enum import Enum
from pydantic import field_serializer
from typing_extensions import TypedDict


class Product(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Product name."""

    EDGE = "edge"
    SEARCH = "search"
    STREAM = "stream"
    LAKE = "lake"


class Role(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Role assigned to the API Credential on the product."""

    ADMIN = "admin"
    EDITOR = "editor"
    READER = "reader"
    USER = "user"
    NOACCESS = "noaccess"


class ProductRoleSchemaTypedDict(TypedDict):
    product: Product
    r"""Product name."""
    role: Role
    r"""Role assigned to the API Credential on the product."""


class ProductRoleSchema(BaseModel):
    product: Product
    r"""Product name."""

    role: Role
    r"""Role assigned to the API Credential on the product."""

    @field_serializer("product")
    def serialize_product(self, value):
        if isinstance(value, str):
            try:
                return models.Product(value)
            except ValueError:
                return value
        return value

    @field_serializer("role")
    def serialize_role(self, value):
        if isinstance(value, str):
            try:
                return models.Role(value)
            except ValueError:
                return value
        return value
