"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apicredentialresponseschema import (
    APICredentialResponseSchema,
    APICredentialResponseSchemaTypedDict,
)
from .defaulterrordto import DefaultErrorDTO, DefaultErrorDTOTypedDict
from cribl_mgmt_plane.types import BaseModel
from cribl_mgmt_plane.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class V1APICredentialsGetAPICredentialRequestTypedDict(TypedDict):
    organization_id: str
    r"""The <code>id</code> of the Organization whose API Credential you want to retrieve."""
    api_credential_id: str
    r"""The <code>clientId</code> of the API Credential to retrieve."""


class V1APICredentialsGetAPICredentialRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>id</code> of the Organization whose API Credential you want to retrieve."""

    api_credential_id: Annotated[
        str,
        pydantic.Field(alias="apiCredentialId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>clientId</code> of the API Credential to retrieve."""


V1APICredentialsGetAPICredentialResponseTypedDict = TypeAliasType(
    "V1APICredentialsGetAPICredentialResponseTypedDict",
    Union[DefaultErrorDTOTypedDict, APICredentialResponseSchemaTypedDict],
)


V1APICredentialsGetAPICredentialResponse = TypeAliasType(
    "V1APICredentialsGetAPICredentialResponse",
    Union[DefaultErrorDTO, APICredentialResponseSchema],
)
