"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane.types import BaseModel
from cribl_mgmt_plane.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class V1APICredentialsDeleteAPICredentialRequestTypedDict(TypedDict):
    organization_id: str
    r"""The <code>id</code> of the Organization whose API Credential you want to delete."""
    api_credential_id: str
    r"""The <code>clientId</code> of the API Credential to delete."""


class V1APICredentialsDeleteAPICredentialRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>id</code> of the Organization whose API Credential you want to delete."""

    api_credential_id: Annotated[
        str,
        pydantic.Field(alias="apiCredentialId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>clientId</code> of the API Credential to delete."""
