"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apicredentialslistresponsedto import (
    APICredentialsListResponseDTO,
    APICredentialsListResponseDTOTypedDict,
)
from .defaulterrordto import DefaultErrorDTO, DefaultErrorDTOTypedDict
from cribl_mgmt_plane.types import BaseModel
from cribl_mgmt_plane.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class V1APICredentialsListAPICredentialsRequestTypedDict(TypedDict):
    organization_id: str
    r"""The <code>id</code> of the Organization whose API Credentials you want to list."""


class V1APICredentialsListAPICredentialsRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>id</code> of the Organization whose API Credentials you want to list."""


V1APICredentialsListAPICredentialsResponseTypedDict = TypeAliasType(
    "V1APICredentialsListAPICredentialsResponseTypedDict",
    Union[APICredentialsListResponseDTOTypedDict, DefaultErrorDTOTypedDict],
)


V1APICredentialsListAPICredentialsResponse = TypeAliasType(
    "V1APICredentialsListAPICredentialsResponse",
    Union[APICredentialsListResponseDTO, DefaultErrorDTO],
)
