"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creditgrantsresponsedto import (
    CreditGrantsResponseDTO,
    CreditGrantsResponseDTOTypedDict,
)
from .defaulterrordto import DefaultErrorDTO, DefaultErrorDTOTypedDict
from cribl_mgmt_plane.types import BaseModel
from cribl_mgmt_plane.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from datetime import datetime
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class V1BillingGetCreditsGrantsRequestTypedDict(TypedDict):
    organization_id: str
    r"""The <code>id</code> of the Organization."""
    starting_on: datetime
    r"""Inclusive start of the query date range in ISO 8601 format. Must be before endingBefore. Minimum range is 1 day. Maximum range is 7 years."""
    ending_before: datetime
    r"""Exclusive end of the query date range in ISO 8601 format. Must be after startingOn. Minimum range is 1 day. Maximum range is 7 years."""


class V1BillingGetCreditsGrantsRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>id</code> of the Organization."""

    starting_on: Annotated[
        datetime,
        pydantic.Field(alias="startingOn"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Inclusive start of the query date range in ISO 8601 format. Must be before endingBefore. Minimum range is 1 day. Maximum range is 7 years."""

    ending_before: Annotated[
        datetime,
        pydantic.Field(alias="endingBefore"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Exclusive end of the query date range in ISO 8601 format. Must be after startingOn. Minimum range is 1 day. Maximum range is 7 years."""


V1BillingGetCreditsGrantsResponseTypedDict = TypeAliasType(
    "V1BillingGetCreditsGrantsResponseTypedDict",
    Union[CreditGrantsResponseDTOTypedDict, DefaultErrorDTOTypedDict],
)


V1BillingGetCreditsGrantsResponse = TypeAliasType(
    "V1BillingGetCreditsGrantsResponse", Union[CreditGrantsResponseDTO, DefaultErrorDTO]
)
