"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .billingwindow import BillingWindow
from .contractsutilizationresponsedto import (
    ContractsUtilizationResponseDTO,
    ContractsUtilizationResponseDTOTypedDict,
)
from .defaulterrordto import DefaultErrorDTO, DefaultErrorDTOTypedDict
from cribl_mgmt_plane import models
from cribl_mgmt_plane.types import BaseModel
from cribl_mgmt_plane.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from datetime import datetime
import pydantic
from pydantic import field_serializer
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class V1BillingGetContractsUtilizationRequestTypedDict(TypedDict):
    organization_id: str
    r"""The <code>id</code> of the Organization."""
    starting_on: datetime
    r"""Inclusive start of the query date range in ISO 8601 format. Must be before endingBefore. Minimum range is 1 day. Maximum range depends on window: 6 months for daily, 7 years for monthly."""
    ending_before: datetime
    r"""Exclusive end of the query date range in ISO 8601 format. Must be after startingOn. Minimum range is 1 day. Maximum range depends on window: 6 months for daily, 7 years for monthly."""
    window: BillingWindow
    r"""Aggregation granularity for credit utilization data. Determines the maximum allowed date range: up to 6 months for daily, up to 7 years for monthly."""


class V1BillingGetContractsUtilizationRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>id</code> of the Organization."""

    starting_on: Annotated[
        datetime,
        pydantic.Field(alias="startingOn"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Inclusive start of the query date range in ISO 8601 format. Must be before endingBefore. Minimum range is 1 day. Maximum range depends on window: 6 months for daily, 7 years for monthly."""

    ending_before: Annotated[
        datetime,
        pydantic.Field(alias="endingBefore"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Exclusive end of the query date range in ISO 8601 format. Must be after startingOn. Minimum range is 1 day. Maximum range depends on window: 6 months for daily, 7 years for monthly."""

    window: Annotated[
        BillingWindow,
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Aggregation granularity for credit utilization data. Determines the maximum allowed date range: up to 6 months for daily, up to 7 years for monthly."""

    @field_serializer("window")
    def serialize_window(self, value):
        if isinstance(value, str):
            try:
                return models.BillingWindow(value)
            except ValueError:
                return value
        return value


V1BillingGetContractsUtilizationResponseTypedDict = TypeAliasType(
    "V1BillingGetContractsUtilizationResponseTypedDict",
    Union[ContractsUtilizationResponseDTOTypedDict, DefaultErrorDTOTypedDict],
)


V1BillingGetContractsUtilizationResponse = TypeAliasType(
    "V1BillingGetContractsUtilizationResponse",
    Union[ContractsUtilizationResponseDTO, DefaultErrorDTO],
)
