"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creditsstatsresponsedto import (
    CreditsStatsResponseDTO,
    CreditsStatsResponseDTOTypedDict,
)
from .defaulterrordto import DefaultErrorDTO, DefaultErrorDTOTypedDict
from cribl_mgmt_plane.types import BaseModel
from cribl_mgmt_plane.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class V1BillingGetCreditsStatsRequestTypedDict(TypedDict):
    organization_id: str
    r"""The <code>id</code> of the Organization."""


class V1BillingGetCreditsStatsRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>id</code> of the Organization."""


V1BillingGetCreditsStatsResponseTypedDict = TypeAliasType(
    "V1BillingGetCreditsStatsResponseTypedDict",
    Union[DefaultErrorDTOTypedDict, CreditsStatsResponseDTOTypedDict],
)


V1BillingGetCreditsStatsResponse = TypeAliasType(
    "V1BillingGetCreditsStatsResponse", Union[DefaultErrorDTO, CreditsStatsResponseDTO]
)
