"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .creditgrantsresponsedto import (
    CreditGrantsResponseDTO,
    CreditGrantsResponseDTOTypedDict,
)
from .defaulterrordto import DefaultErrorDTO, DefaultErrorDTOTypedDict
from cribl_mgmt_plane.types import BaseModel
from cribl_mgmt_plane.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class V1BillingGetCreditsGrantsRequestTypedDict(TypedDict):
    organization_id: str
    r"""The <code>id</code> of the Organization."""


class V1BillingGetCreditsGrantsRequest(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(alias="organizationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The <code>id</code> of the Organization."""


V1BillingGetCreditsGrantsResponseTypedDict = TypeAliasType(
    "V1BillingGetCreditsGrantsResponseTypedDict",
    Union[CreditGrantsResponseDTOTypedDict, DefaultErrorDTOTypedDict],
)


V1BillingGetCreditsGrantsResponse = TypeAliasType(
    "V1BillingGetCreditsGrantsResponse", Union[CreditGrantsResponseDTO, DefaultErrorDTO]
)
