"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .productroleschema import ProductRoleSchema, ProductRoleSchemaTypedDict
from cribl_mgmt_plane import models, utils
from cribl_mgmt_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WorkspaceRole(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Role assigned to the API Credential on the Workspace."""

    OWNER = "owner"
    ADMIN = "admin"
    USER = "user"
    NOACCESS = "noaccess"


class WorkspaceRoleSchemaTypedDict(TypedDict):
    workspace_id: str
    r"""Unique ID of the Workspace."""
    workspace_role: WorkspaceRole
    r"""Role assigned to the API Credential on the Workspace."""
    products: NotRequired[List[ProductRoleSchemaTypedDict]]
    r"""Product-level Roles assigned to the API Credential for the Workspace."""


class WorkspaceRoleSchema(BaseModel):
    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]
    r"""Unique ID of the Workspace."""

    workspace_role: Annotated[WorkspaceRole, pydantic.Field(alias="workspaceRole")]
    r"""Role assigned to the API Credential on the Workspace."""

    products: Optional[List[ProductRoleSchema]] = None
    r"""Product-level Roles assigned to the API Credential for the Workspace."""

    @field_serializer("workspace_role")
    def serialize_workspace_role(self, value):
        if isinstance(value, str):
            try:
                return models.WorkspaceRole(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["products"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
