"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WorkspaceCreateRequestDTOTypedDict(TypedDict):
    workspace_id: str
    r"""Unique identifier for the Workspace."""
    alias: NotRequired[str]
    r"""User-friendly alias for the Workspace."""
    description: NotRequired[str]
    r"""Brief description of the Workspace."""
    tags: NotRequired[List[str]]
    r"""Tags associated with the Workspace."""


class WorkspaceCreateRequestDTO(BaseModel):
    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]
    r"""Unique identifier for the Workspace."""

    alias: Optional[str] = None
    r"""User-friendly alias for the Workspace."""

    description: Optional[str] = None
    r"""Brief description of the Workspace."""

    tags: Optional[List[str]] = None
    r"""Tags associated with the Workspace."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["alias", "description", "tags"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    WorkspaceCreateRequestDTO.model_rebuild()
except NameError:
    pass
