"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_mgmt_plane import models, utils
from cribl_mgmt_plane.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Region(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""AWS region where the workspace is deployed"""

    US_WEST_2 = "us-west-2"
    US_EAST_1 = "us-east-1"
    US_EAST_2 = "us-east-2"
    EU_CENTRAL_1 = "eu-central-1"
    EU_CENTRAL_2 = "eu-central-2"
    EU_WEST_2 = "eu-west-2"
    AP_SOUTHEAST_1 = "ap-southeast-1"
    AP_SOUTHEAST_2 = "ap-southeast-2"
    CA_CENTRAL_1 = "ca-central-1"


class State(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Current state of the workspace"""

    PROVISIONING = "Provisioning"
    ACTIVE = "Active"
    INACTIVE = "Inactive"
    FAILED = "Failed"
    DEPROVISIONING = "Deprovisioning"


class WorkspaceSchemaTypedDict(TypedDict):
    workspace_id: str
    r"""Unique identifier for the workspace"""
    region: Region
    r"""AWS region where the workspace is deployed"""
    leader_fqdn: str
    r"""Fully Qualified Domain Name of the workspace leader"""
    state: State
    r"""Current state of the workspace"""
    alias: NotRequired[str]
    r"""User-friendly alias for the workspace"""
    description: NotRequired[str]
    r"""Detailed description of the workspace"""
    tags: NotRequired[List[str]]
    r"""Tags associated with the workspace"""


class WorkspaceSchema(BaseModel):
    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]
    r"""Unique identifier for the workspace"""

    region: Region
    r"""AWS region where the workspace is deployed"""

    leader_fqdn: Annotated[str, pydantic.Field(alias="leaderFQDN")]
    r"""Fully Qualified Domain Name of the workspace leader"""

    state: State
    r"""Current state of the workspace"""

    alias: Optional[str] = None
    r"""User-friendly alias for the workspace"""

    description: Optional[str] = None
    r"""Detailed description of the workspace"""

    tags: Optional[List[str]] = None
    r"""Tags associated with the workspace"""

    @field_serializer("region")
    def serialize_region(self, value):
        if isinstance(value, str):
            try:
                return models.Region(value)
            except ValueError:
                return value
        return value

    @field_serializer("state")
    def serialize_state(self, value):
        if isinstance(value, str):
            try:
                return models.State(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["alias", "description", "tags"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
